# Generated by Django 3.0.7 on 2020-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
    ]
